# Generated by Django 5.0.1 on 2024-03-05 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 6, 15, 50, 514693, tzinfo=datetime.timezone.utc)),
        ),
    ]
