# Generated by Django 5.0.3 on 2024-03-05 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 5, 10, 53, 48, 695931, tzinfo=datetime.timezone.utc)),
        ),
    ]
